### ISSUE TITLE
[Suggestion] ESModule Oriented Components

### ISSUE THREAD

**Issue by SRNV** [deno-front-end/eon#1]
### **ESModule Oriented Components** (ESMOC)

the idea is to use modules for pattern of the components.
all modules have only one export default, in this suggestion the default export is related to the template of the component

```
export default () => (<template>
  <div></div>
</template>
);

export class Model {}
```

getting the module all the export named are reachable with their name `module.Model`
getting the default export of the module is reachable: `module.default`

### SPA / SSR
changing the way we use the components and change the application's type with the cli
`deno-first-framework --compile-type <type>`

### Required
- deno
- esm imports support
- shouldn't use virtual DOM

### Rendering a List
2 solutions right now:
1. using JSX common way ```array.map(number => <div>{ number }</div>);```
2. using UL and OL as list renderer:
```
 export default <ul
    for={(number) => <OtherComponent number={number}/>}
    of={state.array} />
```
### Strengths
- Typescript support
- es modules are used in both server and browser side

### Constraint
- should use Deno.compile and avoid using tsconfig.json
- how do we get the props of the component
- how to bind all the state to the view ?

**Comment by SRNV** [comment]
![4DBEF4DB-5B70-4811-9DF6-81F09C6DE26B](https://user-images.githubusercontent.com/37340675/97406732-fa49dc80-18f9-11eb-9251-ded85384a5a4.png)

Sketch

**Comment by SRNV** [comment]
sketches

with a function as default, (should bind it to an instance of Model if defined)
![Screenshot from 2020-10-28 10-39-47](https://user-images.githubusercontent.com/37340675/97419373-47ce4580-190a-11eb-94b6-42441c693cf6.png)

with an arrow function as default (can't bind it to an instance, so pass the instance of Model in argument)
![Screenshot from 2020-10-28 10-39-55](https://user-images.githubusercontent.com/37340675/97419377-4866dc00-190a-11eb-8fd3-b1d0bff705cd.png)

**Comment by SRNV** [comment]
update to ViewModel
![Screenshot from 2020-10-28 12-23-40](https://user-images.githubusercontent.com/37340675/97432003-920bf280-191b-11eb-9229-6d052e8f5eee.png)
![Screenshot from 2020-10-28 12-23-46](https://user-images.githubusercontent.com/37340675/97432005-920bf280-191b-11eb-9cdf-d768097621cf.png)

**Comment by ebebbington** [comment]
Note this is my personal opinion 👍 

I think it's best to stay away from default exports, the majority of the JS community dislike them and advise against them, because it can be easier to maintain, i guess in the sense of readability. So from this, i think the effect is *some people* might already start with slightly negative opinions about the framework. Due to type checking, it will help refactoring when using named exports, whereas it's harder to catch when using default exports.

This also opens up the possibility of allow more exports from the module - i know it's probably not on the horizon, **but what if?**

**Comment by ebebbington** [comment]
I'd also find it more readable when using `export <name> = () => {}` as opposed to `export () => { }`

**Comment by SRNV** [comment]
I think we can keep export default and set also an `export const template = (vm: ViewModel) => ()` or `export function template(this: ViewModel){}`
for security

**Comment by ebebbington** [comment]
Are hooks on the horizon? or would a component be defined like:
```
const onNameClick = (event) => {
  ... do stuff
}
const pokemonCard = (name) => {
  return (
    <>
      <p onclick={onNameClick}>{ name }</p>
    </>
  )
}
```

**Comment by SRNV** [comment]
I don't think about hooks because this part isn't reused
```
export default function(this: ViewModel) {
  // nothing here
  return (<template> { this.message } </template>);
}
```

the function will be bound to a proxy of ViewModel and the proxy will return specific instances
once I get these instances I will use a sort of `template.innerHTML`
but all of this is made in the compiler time

**Comment by SRNV** [comment]
![Screenshot from 2020-10-28 18-01-52](https://user-images.githubusercontent.com/37340675/97473415-3d806b80-194b-11eb-94aa-81b85caf5835.png)

**Comment by SRNV** [comment]
keeping in mind that the **default function** is used only to get the dom tree, this create some constraints. specifically to bind the data
what i propose is to use an **arrow function**. this will allow the deno-first-framework graph analyzer to add a **textnode**, replacing **the function**

![Screenshot from 2020-10-29 11-10-21](https://user-images.githubusercontent.com/37340675/97555205-1cb22780-19d8-11eb-93e5-7580bcb8d8a9.png)

the jsx syntax is preserved from template engine like `{{ message }}`.
